<a href="https://colab.research.google.com/github/yrsltn/Integrated-Circuit-Desing-in-Verilog/blob/master/Emotion_Detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install ktrain

     |████████████████████████████████| 25.3MB 137kB/s 
     |████████████████████████████████| 983kB 47.8MB/s 
     |████████████████████████████████| 266kB 46.8MB/s 
     |████████████████████████████████| 1.3MB 48.5MB/s 
     |████████████████████████████████| 471kB 46.9MB/s 
     |████████████████████████████████| 890kB 48.7MB/s 
     |████████████████████████████████| 1.1MB 46.5MB/s 
     |████████████████████████████████| 2.9MB 46.5MB/s 
  Created wheel for ktrain: filename=ktrain-0.25.0-cp36-none-any.whl size=25274500 sha256=ff2067caf43ad3833c257d5b737ad602217aaca310aea4e7b13512b434b44c9f
  Stored in directory: /root/.cache/pip/wheels/5c/73/05/f36d0027bb6575384e21506dbba8db36a7825f15a24f09b2d5
  Created wheel for keras-bert: filename=keras_bert-0.86.0-cp36-none-any.whl size=34145 sha256=336e9aa686fa0b61ac42977de0a334aafe2759fce43269b9c6258659df94ece8
  Stored in directory: /root/.cache/pip/wheels/66/f0/b1/748128b58562fc9e31b907bb5e2ab6a35eb37695e83911236b
  Created wheel for lan

In [ ]:
import numpy as np 
import pandas as pd 
import os
import ktrain
from ktrain import text

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Data uploading from DRIVE
test = pd.read_csv('/content/drive/MyDrive/BDproject/test.txt',sep=";",header=None, names=['sentence','label'])
train = pd.read_csv('/content/drive/MyDrive/BDproject/train.txt',sep=";",header=None, names=['sentence','label'])
val = pd.read_csv('/content/drive/MyDrive/BDproject/val.txt',sep=";",header=None, names=['sentence','label'])

MAX_LEN = 256


In [ ]:
# Splitting X and Y
x_train = train.iloc[:,0] 
y_train = train.iloc[:,1] 

x_test = test.iloc[:,0] 
y_test = test.iloc[:,1] 

x_val = test.iloc[:,0] 
y_val = test.iloc[:,1] 

x_train,y_train = np.array(x_train),np.array(y_train)
x_test,y_test = np.array(x_test),np.array(y_test)
x_val,y_val = np.array(x_val),np.array(y_val)

print(x_train.shape,"|",y_train.shape)
print(x_test.shape,"|",y_test.shape)
print(x_val.shape,"|",y_val.shape)

(16000,) | (16000,)
(2000,) | (2000,)
(2000,) | (2000,)


In [ ]:
print(train.iloc[:,1].value_counts())

int_y_train = []
int_y_test = []
int_y_val = []

for l in y_train:
    
    if l == "joy":        
        int_y_train.append(0)
        
    if l == "sadness":       
        int_y_train.append(1)            
    if l == "anger":      
        int_y_train.append(2)      
    if l == "fear":
        int_y_train.append(3)
    if l == "love":
        int_y_train.append(4)
    if l == "surprise":
        int_y_train.append(5)
        
        
for l in y_test:
    
    if l == "joy":        
        int_y_test.append(0)
        
    if l == "sadness":       
        int_y_test.append(1)            
    if l == "anger":      
        int_y_test.append(2)      
    if l == "fear":
        int_y_test.append(3)
    if l == "love":
        int_y_test.append(4)
    if l == "surprise":
        int_y_test.append(5)
        
for l in y_val:
    
    if l == "joy":        
        int_y_val.append(0)
        
    if l == "sadness":       
        int_y_val.append(1)            
    if l == "anger":      
        int_y_val.append(2)      
    if l == "fear":
        int_y_val.append(3)
    if l == "love":
        int_y_val.append(4)
    if l == "surprise":
        int_y_val.append(5)
        


        
int_y_train,int_y_test,int_y_val = np.array(int_y_train),np.array(int_y_test),np.array(int_y_val)
from sklearn import preprocessing
from keras.utils import np_utils

le = preprocessing.LabelEncoder()
le.fit(int_y_train)

encoded_y_train = le.transform(int_y_train)
encoded_y_test = le.transform(int_y_test)
encoded_y_val = le.transform(int_y_val)

encoded_y_train = np_utils.to_categorical(encoded_y_train)
encoded_y_test = np_utils.to_categorical(encoded_y_test)
encoded_y_val = np_utils.to_categorical(encoded_y_val)

print(encoded_y_train)

print(int_y_train[:10])

joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: label, dtype: int64
[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
[1 1 2 4 2 1 5 3 0 4]


In [ ]:
class_names = ['joy', 'sadness', 'anger', 'fear', 'love', 'surprise' ]

x_train_bert = x_train
y_train_bert = encoded_y_train
x_test_bert = x_test
(x_train_bert,  y_train_bert), (x_test_bert, y_test_bert), preproc = text.texts_from_array(x_train=x_train_bert, y_train=y_train_bert,

x_test=x_test, y_test=encoded_y_test,
class_names=class_names,
preprocess_mode='bert',
maxlen=MAX_LEN, 
max_features=35000)

downloading pretrained BERT model (uncased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en


Is Multi-Label? False
preprocessing test...
language: en


task: text classification


In [ ]:
#BERT Training and validation

model_bert = text.text_classifier('bert', train_data=(x_train_bert, y_train_bert), preproc=preproc)

Is Multi-Label? False
maxlen is 350
done.


In [ ]:
learner = ktrain.get_learner(model_bert, train_data=(x_train_bert, y_train_bert), 
                             val_data=(x_test_bert, encoded_y_test),
                             batch_size=6)

In [ ]:
learner.fit_onecycle(2e-5, 3)



begin training using onecycle policy with max lr of 2e-05...
Epoch 1/3
2667/2667 [==============================] - 2015s 756ms/step - loss: 0.6770 - accuracy: 0.7526 - val_loss: 0.2159 - val_accuracy: 0.9200
Epoch 2/3
2667/2667 [==============================] - 2009s 753ms/step - loss: 0.1663 - accuracy: 0.9323 - val_loss: 0.1514 - val_accuracy: 0.9300
Epoch 3/3
2667/2667 [==============================] - 2003s 751ms/step - loss: 0.0900 - accuracy: 0.9519 - val_loss: 0.1360 - val_accuracy: 0.9370


In [ ]:
#validation of BERT
learner.validate(val_data=(x_test_bert, encoded_y_test), class_names=class_names)

              precision    recall  f1-score   support

         joy       0.97      0.94      0.96       695
     sadness       0.97      0.98      0.97       581
       anger       0.95      0.90      0.93       275
        fear       0.92      0.88      0.90       224
        love       0.81      0.93      0.87       159
    surprise       0.72      0.89      0.80        66

    accuracy                           0.94      2000
   macro avg       0.89      0.92      0.90      2000
weighted avg       0.94      0.94      0.94      2000



array([[654,   1,   2,   0,  35,   3],
       [  3, 569,   5,   4,   0,   0],
       [  3,  14, 248,  10,   0,   0],
       [  0,   3,   5, 196,   0,  20],
       [ 11,   0,   0,   0, 148,   0],
       [  3,   1,   0,   3,   0,  59]])

In [ ]:
#Predicting with BERT
predictor = ktrain.get_predictor(learner.model, preproc)
predictor.get_classes()

['joy', 'sadness', 'anger', 'fear', 'love', 'surprise']

In [ ]:
import nltk

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
text = 'I am very happy. I just broke up with my girlfriend. He is cute. I love you. I hate you. Lets go get drink'
a_list = nltk.tokenize.sent_tokenize(text)
n=len(a_list)
a=0
b=0
c=0
d=0
e=0
f=0
for i in range (0,n):

  start_time = time.time() 
  prediction = predictor.predict(a_list[i])
  if prediction=='joy':
    a=a+1
  if prediction=='sadness':
    b=b+1
  if prediction=='anger':
    c=c+1
  if prediction=='fear':
    d=d+1 
  if prediction=='love':
    e=e+1 
  if prediction=='surprise':
    f=f+1
  print(prediction)
t = (a+b+c+d+e+f)
proba = {'anger': c, 'joy': a, 'sadness':b, 'love':e, 'surprise':f, 'fear':d}             
emotion = max(proba, key=proba.get)  
z = max(a,b,c,d,e,f)  
percentage = z/t*100
print('predicted emotion of the text is: ' + emotion + ' with ' + "{:.2f}".format(percentage) + '%')




joy


sadness


joy


love


anger


joy
predicted emotion of the text is: joy with 50.00%


In [ ]:
#Sequential model of RNN
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords = stopwords.words('english')

x_train_cl = []
x_test_cl = []
x_val_cl = []


# Deleting stopwords
for text in x_train:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_train_cl.append(text)
    
for text in x_test:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_test_cl.append(text)

for text in x_val:
    
    text = text.split()
    text = [word for word in text if word not in stopwords]
    text = " ".join(text)
    x_val_cl.append(text)
    
x_train,x_test,x_val = np.array(x_train_cl),np.array(x_test_cl),np.array(x_val_cl)

# We use total_text for fitting tokenizer in general 
total_text = np.concatenate((x_train,x_test,x_val),axis=0)

num_words = 2000

tokenizer = Tokenizer(num_words = num_words) 

tokenizer.fit_on_texts(total_text)

list(tokenizer.word_index)[:10]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


['feel',
 'feeling',
 'like',
 'im',
 'really',
 'know',
 'time',
 'get',
 'little',
 'people']

In [ ]:
# Tokenizing everything

x_train_token = tokenizer.texts_to_sequences(x_train)
x_test_token = tokenizer.texts_to_sequences(x_test)
x_val_token = tokenizer.texts_to_sequences(x_val)

total_token = np.concatenate((x_train_token,x_test_token,x_val_token),axis=0)

In [ ]:
# Padding
print(np.mean([len(text) for text in total_token]))

7.6699


In [ ]:
x_train_pad = pad_sequences(x_train_token,20) 
x_test_pad = pad_sequences(x_test_token,20)
x_val_pad = pad_sequences(x_val_token,20)

print(x_train_pad[0],end="\n-------------------------------------------------------------------------\n")
print(x_train_pad[1])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  50
   1 495]
-------------------------------------------------------------------------
[   0    0    0    0    0    0    0    0    0    0    0    0   30    2
  464  425   44   54 1573 1304]


In [ ]:
#Sequential Modeling and Predicting
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense,CuDNNGRU,Embedding,Bidirectional


model = Sequential()

model.add(Embedding(input_dim=2000
                   ,output_dim=100
                   ,input_length=20))

model.add(Bidirectional(CuDNNGRU(units=16,return_sequences=True)))

model.add(Bidirectional(CuDNNGRU(units=8)))

model.add(Dense(6,activation="softmax"))

model.compile(loss="categorical_crossentropy",optimizer="rmsprop",metrics=["accuracy"])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 100)           200000    
_________________________________________________________________
bidirectional (Bidirectional (None, 20, 32)            11328     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 16)                2016      
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 102       
Total params: 213,446
Trainable params: 213,446
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(x_train_pad.shape)
print(y_train.shape)
model.fit(x_train_pad,encoded_y_train,epochs=10,batch_size=20)

(16000, 20)
(16000,)
Epoch 1/10
800/800 [==============================] - 6s 8ms/step - loss: 1.1830 - accuracy: 0.5272
Epoch 2/10
800/800 [==============================] - 6s 8ms/step - loss: 0.4375 - accuracy: 0.8611
Epoch 3/10
800/800 [==============================] - 6s 8ms/step - loss: 0.2453 - accuracy: 0.9186
Epoch 4/10
800/800 [==============================] - 6s 8ms/step - loss: 0.1771 - accuracy: 0.9334
Epoch 5/10
800/800 [==============================] - 6s 8ms/step - loss: 0.1453 - accuracy: 0.9415
Epoch 6/10
800/800 [==============================] - 6s 8ms/step - loss: 0.1288 - accuracy: 0.9488
Epoch 7/10
800/800 [==============================] - 6s 8ms/step - loss: 0.1173 - accuracy: 0.9524
Epoch 8/10
800/800 [==============================] - 6s 8ms/step - loss: 0.1079 - accuracy: 0.9557
Epoch 9/10
800/800 [==============================] - 6s 8ms/step - loss: 0.0985 - accuracy: 0.9603
Epoch 10/10
800/800 [==============================] - 6s 8ms/step - loss: 0.09

In [ ]:
#Predicting with the sequential RNN
preds = model.predict_classes(x_test_pad)
from sklearn.metrics import accuracy_score

accuracy_score(preds,int_y_test)


0.9245

In [ ]:
message = 'I love you'
message_sequential = message
message_sequential_token = tokenizer.texts_to_sequences(message_sequential)
message_sequential_pad = pad_sequences(message_sequential_token,20) 


flat_list = []
for sublist in message_sequential_pad:
    for item in sublist:
        flat_list.append(item)

flat_list = [flat_list]

message_sequential = pad_sequences(flat_list, padding='post', maxlen=MAX_LEN)

model.predict(message_sequential)*100



array([[ 3.033682  , 14.613419  , 57.593803  , 24.412458  ,  0.19847986,
         0.14815678]], dtype=float32)

In [ ]:
#Final Model which combines two above trained algorithms
text = 'i never make her separate from me because i don t ever want her to feel like i m ashamed with her. i left with my bouquet of red and yellow tulips under my arm feeling slightly more optimistic than when i arrived. i cant walk into a shop anywhere where i do not feel uncomfortable. i felt anger when at the end of a telephone call. i like to have the same breathless feeling as a reader eager to see what will happen next'
a_list = nltk.tokenize.sent_tokenize(text)
n=len(a_list)
a=0
b=0
c=0
d=0
e=0
f=0
a_rnn=0
b_rnn=0
c_rnn=0
d_rnn=0
e_rnn=0
f_rnn=0

for i in range (0,n):

  start_time = time.time() 
  words_list = word_tokenize(a_list[i])
  
  words_quantity = len(words_list)

  text_sequential_token = tokenizer.texts_to_sequences(a_list[i])
  text_sequential_pad = pad_sequences(text_sequential_token,20)

  flat_list = []
  for sublist in text_sequential_pad:
      for item in sublist:
          flat_list.append(item)

  flat_list = [flat_list]

  text_sequential = pad_sequences(flat_list, padding='post', maxlen=MAX_LEN)
  
  prediction_rnn=model.predict(text_sequential_pad)
  prediction = predictor.predict(a_list[i])
  emotion_rnn = y_val[prediction_rnn.argmax()]
  
  if prediction=='joy':
    a=(a+1)*words_quantity
  if prediction=='sadness':
    b=(b+1)*words_quantity
  if prediction=='anger':
    c=(c+1)*words_quantity
  if prediction=='fear':
    d=(d+1)*words_quantity 
  if prediction=='love':
    e=(e+1)*words_quantity
  if prediction=='surprise':
    f=(f+1)*words_quantity

  if emotion_rnn=='joy':
    a_rnn=(a_rnn+1)*words_quantity
  if emotion_rnn=='sadness':
    b_rnn=(b_rnn+1)*words_quantity
  if emotion_rnn=='anger':
    c_rnn=(c_rnn+1)*words_quantity
  if emotion_rnn=='fear':
    d_rnn=(d_rnn+1)*words_quantity
  if emotion_rnn=='love':
    e_rnn=(e_rnn+1)*words_quantity 
  if emotion_rnn=='surprise':
    f_rnn=(f_rnn+1)*words_quantity

  print('--------------------------------------------------------------------------')
  print('Sentence: {} \nPredicted_bert: {}'.format(a_list[i], prediction))
  print('Predicted_rnn: {}'.format(emotion_rnn))
  print('Word number:',words_quantity)

t = (a+b+c+d+e+f)
t_rnn = (a_rnn+b_rnn+c_rnn+d_rnn+e_rnn+f_rnn)
total = t+t_rnn

proba = {'anger': c, 'joy': a, 'sadness':b, 'love':e, 'surprise':f, 'fear':d}             
proba_rnn = {'anger': c_rnn, 'joy': a_rnn, 'sadness':b_rnn, 'love':e_rnn, 'surprise':f_rnn, 'fear':d_rnn}             
emotion_bert = max(proba, key=proba.get)
emotion_rnn_1 = max(proba_rnn, key=proba_rnn.get)

numbers = [a,b,c,d,e,f]
numbers_rnn = [a_rnn,b_rnn,c_rnn,d_rnn,e_rnn,f_rnn]
z = max(numbers)
z_rnn = max(numbers_rnn)
percentage_bert = z/total*100
percentage_rnn = z_rnn/total*100


if percentage_bert >= percentage_rnn:
  emotion = emotion_bert
  percentage = percentage_bert
  new1 = proba_rnn.get(emotion_bert)
  numbers_rnn.remove(new1)
  second_largest_integer_rnn = max(numbers_rnn)
  numbers.remove(z)
  second_largest_integer = max(numbers)
  proba.pop(emotion_bert)
  proba_rnn.pop(emotion_bert)
  
else: 
  emotion = emotion_rnn_1
  percentage = percentage_rnn
  new1 = proba.get(emotion_rnn_1)
  numbers_rnn.remove(z_rnn)
  second_largest_integer_rnn = max(numbers_rnn)
  numbers.remove(new1)
  second_largest_integer = max(numbers)
  proba.pop(emotion_rnn_1)
  proba_rnn.pop(emotion_rnn_1)

emotion_bert_2 = max(proba, key=proba.get)
emotion_rnn_2 = max(proba_rnn, key=proba_rnn.get)
percentage_bert_2 = second_largest_integer/total*100
percentage_rnn_2 = second_largest_integer_rnn/total*100

if percentage_bert_2 > percentage_rnn_2:
  emotion2 = emotion_bert_2
  percentage2 = percentage_bert_2
else: 
  emotion2 = emotion_rnn_2
  percentage2 = percentage_rnn_2
print('--------------------------------------------------------------------------')
print('Predicted emotion of the full text is: ' + emotion + ' with ' + "{:.2f}".format(percentage) + '% '+'and ' + emotion2 + ' with ' + "{:.2f}".format(percentage2)+'%')
print('--------------------------------------------------------------------------')


--------------------------------------------------------------------------
Sentence: i never make her separate from me because i don t ever want her to feel like i m ashamed with her. 
Predicted_bert: sadness
Predicted_rnn: love
Word number: 23


--------------------------------------------------------------------------
Sentence: i left with my bouquet of red and yellow tulips under my arm feeling slightly more optimistic than when i arrived. 
Predicted_bert: joy
Predicted_rnn: anger
Word number: 22


--------------------------------------------------------------------------
Sentence: i cant walk into a shop anywhere where i do not feel uncomfortable. 
Predicted_bert: fear
Predicted_rnn: fear
Word number: 14


--------------------------------------------------------------------------
Sentence: i felt anger when at the end of a telephone call. 
Predicted_bert: anger
Predicted_rnn: joy
Word number: 12


--------------------------------------------------------------------------
Sentence: i like to have the same breathless feeling as a reader eager to see what will happen next 
Predicted_bert: joy
Predicted_rnn: joy
Word number: 18
--------------------------------------------------------------------------
Predicted emotion of the full text is: joy with 54.76% and love with 3.04%
--------------------------------------------------------------------------
